
name: BLENDERMALT_ADDON_PACKAGE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    #branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Package Shader Examples
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Shader Examples
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/Shader Examples
  
  package-blender:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: package_blender.py
      run: python package_blender.py
      working-directory: ${{ github.workspace }}/.github/workflows
    
    - name: Package Addon
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: BlenderMalt-${{ runner.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/BlenderMalt*

    - name: Package Blender
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ env._BLENDER_FILE }}
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/.github/workflows/${{ env._BLENDER_FILE }}

